# Generated by Django 4.1.7 on 2023-04-01 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='created_at',
        ),
    ]
