# Generated by Django 4.1.7 on 2023-04-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_guess_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='definition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
