# Generated by Django 4.1.7 on 2023-04-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_guess_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('similarity', models.FloatField()),
                ('definition', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-word'],
            },
        ),
    ]
